"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = void 0;
const express_1 = require("express");
const models_1 = require("../../models");
const controllers_1 = require("../controllers");
const middlewares_1 = require("../middlewares");
const validators_1 = require("../validators");
exports.userRouter = express_1.Router();
exports.userRouter.get('/users', middlewares_1.PermissionAuthorizer(models_1.UserPermission.admin), middlewares_1.Paginate, validators_1.UserValidator.onGetUsers, controllers_1.UserController.onGetUsers);
exports.userRouter.get('/users/:id', middlewares_1.Authorizer, validators_1.UserValidator.onGetUser, controllers_1.UserController.onGetUser);
exports.userRouter.delete('/users/:id', middlewares_1.Authorizer, validators_1.UserValidator.onDeleteUser, controllers_1.UserController.onDeleteUser);
exports.userRouter.patch('/users/:id', middlewares_1.Authorizer, validators_1.UserValidator.onUpdateUser, controllers_1.UserController.onUpdateUser);
exports.userRouter.get('/user_permission_requests', middlewares_1.PermissionAuthorizer(models_1.UserPermission.admin), validators_1.UserValidator.onGetUserRequests, controllers_1.UserController.onGetUserRequests);
exports.userRouter.get('/user_permission_requests/:id', middlewares_1.Authorizer, validators_1.UserValidator.onGetUserRequest, controllers_1.UserController.onGetUserRequest);
exports.userRouter.post('/user_permission_requests', middlewares_1.Authorizer, validators_1.UserValidator.onCreateUserRequest, controllers_1.UserController.onCreateUserRequest);
exports.userRouter.delete('/user_permission_requests/:id', middlewares_1.Authorizer, validators_1.UserValidator.onDeleteUserRequest, controllers_1.UserController.onDeleteUserRequest);
exports.userRouter.put('/user_permission_requests/:id', middlewares_1.Authorizer, validators_1.UserValidator.onUpdateUserRequest, controllers_1.UserController.onUpdateUserRequest);
