myNextApplication:
  component: '@sls-next/serverless-component@latest'
  inputs:
    name: blog-client
    description: blog-client
    bucketName: blog-client
    publicDirectoryCache:
      value: public, max-age=604800
      test: /\.(gif|jpe?g|png|txt|xml)$/i
    cloudfront:
      distributionId: 'E34CY2UQYHDPWB'
