service: alpox-util-server
disabledDeprecations:
  - "*"
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: prod
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: alpox-blog-util-server
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
    noPrependStageInUrl: true

functions:
  image:
    handler: handler.upload
    description: "Blog Image Server"
    timeout: 20
    memorySize: 2048
    events:
      - http: POST /upload
