/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TestIndexBody {
  /**
   * 소셜 토큰
   */
  accessToken: string;
  /**
   * 소셜 타입
   */
  socialType?: "KAKAO" | "NAVER";
  [k: string]: unknown;
}
